### PR TITLE
Start of login pages or GitHub and empty landing page for project

### PR DESCRIPTION
**Pull request by jscharber**
dashboards
image
image

### CODE REVIEW

**Comment by rick4106t** [comment]
Seems the black font is hard to read for microsoft and google and impossible to read for github or bitbucket. White font would be better

**Review by rick4106t — CHANGES_REQUESTED** [review]
per my last comment, the font color should be white for the badges.

**Comment by jscharber** [comment]
It is a bootstrap 3.3 vs 4.0 issue.  I don't think social icons have been updated.  Mark it as an issue to work on.

/jms

**Review by rick4106t — APPROVED** [review]

**Review by MarkGreenPR — APPROVED** [review]

**Comment by jscharber** [comment]
Change text color to white
image

**Comment by rick4106t** [comment]
looks great!

**Pull request merged**
